class_based_view/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from unicodedata import name
from django.urls import path
from .views import(
    IndexView, HomeView, BookDetailView,
   BookListView, BookCreateView, BookUpdateView,
   BookDeleteView, BookFormView,BookRedirectView,
   delete_picture
  )
# from django.views.generic.base import TemplateView
from django.views.generic.base import RedirectView

app_name  = 'store'

urlpatterns = [
  path('index/', IndexView.as_view(), name='index'),
  # path('home/', TemplateView.as_view(template_name='home.html'),name='home')
  path('home/<name>', HomeView.as_view(), name='home'),
  path('detail_book/<int:pk>', BookDetailView.as_view(), name='detail_book'),
  path('list_books/',BookListView.as_view(), name='list_books'),
  path('list_books/<name>',BookListView.as_view(), name='list_books'),
  path('add_book/', BookCreateView.as_view(), name='add_book'),
  path('edit_book/<int:pk>', BookUpdateView.as_view(), name='edit_book'),
  path('delete_book/<int:pk>', BookDeleteView.as_view(), name='delete_book'),
  path('book_form/', BookFormView.as_view(), name='book_form'),
  path('google/', RedirectView.as_view(url='https://google.co.jp')),
  path('book_redirect_view/', BookRedirectView.as_view(), name='book_redirect_view'),
  path('book_redirect_view/<int:pk>', BookRedirectView.as_view(), name='book_redirect_view'),
  path('delete_picture/<int:pk>',delete_picture, name='delete_picture' ),
]


store/models.py
from email.mime import application
from django.db import models
from django.urls import reverse_lazy
from django.dispatch import receiver
import os
import logging

application_logger = logging.getLogger('application-logger')

class BaseModel(models.Model):
  create_at = models.DateTimeField()
  update_at = models.DateTimeField()

  class Meta:
    abstract = True


class Books(BaseModel):
  name = models.CharField(max_length=255)
  description = models.CharField(max_length=1000)
  price = models.IntegerField()

  class Meta:
    db_table = 'books'

  def get_absolute_url(self):
    return reverse_lazy('store:detail_book', kwargs={'pk':self.pk})

class PicturesManager(models.Manager):
  def filter_by_book(self, book):
    return self.filter(book=book).all()

class Pictures(BaseModel):

  picture = models.FileField(upload_to='picture/')
  book = models.ForeignKey(
    'books', on_delete=models.CASCADE
  )
  objects = PicturesManager()

@receiver(models.signals.post_delete, sender=Pictures)
def delete_picture(sender, instance, **kwargs):
  if instance.picture:
    if os.path.isfile(instance.picture.path):
      os.remove(instance.picture.path)
      application_logger.info(f'{instance.picture.path}を削除しました')

templates/add_book.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="保存">
</form>

templates/book.html
{{ object.name }}<br>
{{ object.description }}<br>
{{ object.price }}円<br>

templates/book_list.html
<p><a href="{% url 'store:add_book' %}">データの追加</a></p>
<table>
  <tbody>
  {% for object in object_list %}
  <tr>
    <td>名前: <a href="{{ object.get_absolute_url }}">{{ object.name }}</a></td>
    <td>説明:{{ object.description }}</td>
    <td><a href="{% url 'store:edit_book' object.id %}">編集</a></td>
    <td><a href="{% url 'store:delete_book' object.id %}">削除</a></td>
    <td>
      {% for picture in object.pictures_set.all %}
        <img width="20px" height="20px" src={{ picture.picture.url }}>
      {% endfor %}
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>

templates/delete_book.html
<form method="POST">
{% csrf_token %}
<p>{{ object.name }}削除してもよろしいですか？</p>
<input type="submit" value="削除する">
</form>

templates/form_book.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="保存">
</form>

templates/home.html
<h1>Home画面</h1>
<p>{{ name }}さん。現在時刻は{{ time }}です</p>

templates/index.html
<h1>indexページです</h1>
<form method="POST">
{% csrf_token %} 
{{ book_form.as_p }}
<input type="submit" value="送信">
</form>

templates/update_book.html
{% if messages %}
{% for message in messages %}
  {{ message.message }}
{% endfor %}
{% endif %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <hr>
  {% for picture in pictures %}
    <a href="{% url 'store:delete_picture' pk=picture.id %}"><img width="100px" height="100px" src="{{ picture.picture.url }}"></a>
  {% endfor %}
  {{ picture_form.as_p }}
  <input type="submit" value="更新">
</form>

<style>
img:hover{
  opacity: 0.2;
}
</style>